### ISSUE TITLE
Binary XML file line #130: Error inflating class

### ISSUE THREAD

**Issue by makazemi** [josinSbazin/android_ExpandableLayout#15]
@josinSbazin : I get this error when I use in java application:
Binary XML file line #130: Error inflating class ru.rhanza.constraintexpandablelayout.ExpandableLayout
should I import kotlin module to my project?

**Comment by mohan-dev1248** [comment]
It's there in Kotlin project too. I tried putting it inside another Layouts and the root element to be Expandable Layout, it still shows Error inflating the class. Also I tried the latest version 0.7, the one mentioned in ReadMe file is 0.5 it seems

**Comment by josinSbazin** [comment]
> It's there in Kotlin project too. I tried putting it inside another Layouts and the root element to be Expandable Layout, it still shows Error inflating the class. Also I tried the latest version 0.7, the one mentioned in ReadMe file is 0.5 it seems

can you show an example of xml and build gradle dependencies where the library is used?
I will try to help.

**Comment by josinSbazin** [comment]
@mohan-dev1248 @makazemi 
Can't reproduce this bug.
If you show stacktrace, maybe, i can help
