### ISSUE TITLE
Replace the expanded text

### ISSUE THREAD

**Issue by BaiMingxu1** [josinSbazin/android_ExpandableLayout#18]
How do you change the expanded text? Now, whether it's unfolding or folding is a kind of text, I want to fold when the text is expanded, expanded state text is folded, how to achieve? thank you

**Comment by josinSbazin** [comment]
Sorry. Could you please clarify what do you mean with example? I can't understand you(

**Comment by josinSbazin** [comment]
@BaiMingxu1
If i understood you correctly, you can change text on more button when state is changed like this:
```kotlin
expandableLayout.onStateChangeListener { oldState: State, newState: State ->
   when (newState) {
          Collapsed -> expandableLayout.moreText = "collapsed text"
          Expanded -> expandableLayout.moreText = "expanded text"
   }
}
```
